spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/bookmyshow
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: eShop
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
---
spring:
  config:
    activate.on-profile: dev
  jpa:
    show-sql: false
server:
  port: 8081
---
spring:
  config:
    activate.on-profile: qa
server:
  port: 8082